# Generated by Django 2.1.7 on 2019-04-17 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=200)),
                ('enquiry_made', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyapp.Enquiry')),
            ],
        ),
    ]
