# Generated by Django 2.1.7 on 2019-04-09 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_description', models.TextField(max_length=200)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('enquiry_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enquiry_property', models.ManyToManyField(to='propertyapp.Property')),
            ],
        ),
    ]
