# Generated by Django 2.1.7 on 2019-04-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0002_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_person',
        ),
    ]
