# Generated by Django 2.1.7 on 2019-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0003_remove_enquiry_enquiry_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_person_mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
