# Generated by Django 2.1.7 on 2019-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
