# Generated by Django 2.1.7 on 2019-04-02 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_auto_20190402_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_image',
            field=models.ImageField(upload_to='media/user_images/'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
