# Generated by Django 2.1.7 on 2019-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0003_auto_20190402_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email_field',
            field=models.EmailField(default='No Mail Given', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='profile_image',
            field=models.ImageField(default='static/register_app/blank_face.png', upload_to='media/user_images/'),
        ),
    ]
