# Generated by Django 2.1.7 on 2019-04-03 04:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('registerapp', '0005_auto_20190403_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_field', models.EmailField(default='No Mail Given', max_length=30, unique=True)),
                ('description', models.TextField(default='No Description Given')),
                ('profile_image', models.ImageField(default='static/register_app/blank_face.png', upload_to='media/user_images/')),
                ('is_seller', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
